In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [10]:
data = pd.read_csv('result_new.csv')
X = data.drop('y', axis=1)
y = data['y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [11]:
# svclassifier = SVC(kernel='linear')
# svclassifier.fit(X_train, y_train)
# y_pred = svclassifier.predict(X_test)
# print(confusion_matrix(y_test,y_pred))
# print(classification_report(y_test,y_pred))

In [12]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1589   30   20    3  112]
 [ 135   85   93    2  253]
 [  63    8 3309  101  242]
 [  23    0  123 1048    0]
 [  68   18  174    1 1412]]
              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1754
           1       0.60      0.15      0.24       568
           2       0.89      0.89      0.89      3723
           3       0.91      0.88      0.89      1194
           4       0.70      0.84      0.76      1673

    accuracy                           0.84      8912
   macro avg       0.79      0.73      0.73      8912
weighted avg       0.83      0.84      0.82      8912

